# based on https://github.com/gchq/stroom-docs/blob/master/.travis.yml
language: node_js
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

install:
  #- . $HOME/.nvm/nvm.sh
  #- nvm install stable
  #- nvm use stable
  #- npm install
  #- npm install -g gitbook-cli
  #- npm list -g
  #- cd /home/travis/.nvm/versions/node/v16.1.0/lib/node_modules/gitbook-cli && npm install graceful-fs@4.2.0 --save-dev
  - npm install -g honkit --save-dev

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- honkit install
    - honkit build

before_deploy:
  #Ensure we are in the right dir
  - cd ${TRAVIS_BUILD_DIR}

deploy:
    #Push the generated gitbook html to the gh-pages branch
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _book
    target_branch: gh-pages
    on:
      branch: master

branches:
  only:
    - master

notifications:
  email:
    on_success: never
