name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2

    - name: Install
      shell: bash
      run: |
          npm install
          npm install honkit
          
    - name: Build
      shell: bash
      run: |
          npx honkit build

